export const COUNTRY_CODES = [
  { name: 'India',                   dialCode: '+91',  isoCode: 'IN', maxLength: 10 },
  { name: 'Afghanistan',             dialCode: '+93',  isoCode: 'AF', maxLength: 9  },
  { name: 'Albania',                 dialCode: '+355', isoCode: 'AL', maxLength: 9  },
  { name: 'Algeria',                 dialCode: '+213', isoCode: 'DZ', maxLength: 9  },
  { name: 'Andorra',                 dialCode: '+376', isoCode: 'AD', maxLength: 6  },
  { name: 'Angola',                  dialCode: '+244', isoCode: 'AO', maxLength: 9  },
  { name: 'Argentina',               dialCode: '+54',  isoCode: 'AR', maxLength: 10 },
  { name: 'Armenia',                 dialCode: '+374', isoCode: 'AM', maxLength: 8  },
  { name: 'Australia',               dialCode: '+61',  isoCode: 'AU', maxLength: 9  },
  { name: 'Austria',                 dialCode: '+43',  isoCode: 'AT', maxLength: 13 },
  { name: 'Azerbaijan',              dialCode: '+994', isoCode: 'AZ', maxLength: 9  },
  { name: 'Bahrain',                 dialCode: '+973', isoCode: 'BH', maxLength: 8  },
  { name: 'Bangladesh',              dialCode: '+880', isoCode: 'BD', maxLength: 10 },
  { name: 'Belarus',                 dialCode: '+375', isoCode: 'BY', maxLength: 9  },
  { name: 'Belgium',                 dialCode: '+32',  isoCode: 'BE', maxLength: 9  },
  { name: 'Belize',                  dialCode: '+501', isoCode: 'BZ', maxLength: 7  },
  { name: 'Benin',                   dialCode: '+229', isoCode: 'BJ', maxLength: 8  },
  { name: 'Bhutan',                  dialCode: '+975', isoCode: 'BT', maxLength: 8  },
  { name: 'Bolivia',                 dialCode: '+591', isoCode: 'BO', maxLength: 8  },
  { name: 'Bosnia and Herzegovina',  dialCode: '+387', isoCode: 'BA', maxLength: 8  },
  { name: 'Botswana',                dialCode: '+267', isoCode: 'BW', maxLength: 8  },
  { name: 'Brazil',                  dialCode: '+55',  isoCode: 'BR', maxLength: 11 },
  { name: 'Brunei',                  dialCode: '+673', isoCode: 'BN', maxLength: 7  },
  { name: 'Bulgaria',                dialCode: '+359', isoCode: 'BG', maxLength: 9  },
  { name: 'Burkina Faso',            dialCode: '+226', isoCode: 'BF', maxLength: 8  },
  { name: 'Cambodia',                dialCode: '+855', isoCode: 'KH', maxLength: 9  },
  { name: 'Cameroon',                dialCode: '+237', isoCode: 'CM', maxLength: 9  },
  { name: 'Canada',                  dialCode: '+1',   isoCode: 'CA', maxLength: 10 },
  { name: 'Chile',                   dialCode: '+56',  isoCode: 'CL', maxLength: 9  },
  { name: 'China',                   dialCode: '+86',  isoCode: 'CN', maxLength: 11 },
  { name: 'Colombia',                dialCode: '+57',  isoCode: 'CO', maxLength: 10 },
  { name: 'Costa Rica',              dialCode: '+506', isoCode: 'CR', maxLength: 8  },
  { name: 'Croatia',                 dialCode: '+385', isoCode: 'HR', maxLength: 9  },
  { name: 'Cuba',                    dialCode: '+53',  isoCode: 'CU', maxLength: 8  },
  { name: 'Cyprus',                  dialCode: '+357', isoCode: 'CY', maxLength: 8  },
  { name: 'Czech Republic',          dialCode: '+420', isoCode: 'CZ', maxLength: 9  },
  { name: 'Denmark',                 dialCode: '+45',  isoCode: 'DK', maxLength: 8  },
  { name: 'Dominican Republic',      dialCode: '+1',   isoCode: 'DO', maxLength: 10 },
  { name: 'Ecuador',                 dialCode: '+593', isoCode: 'EC', maxLength: 9  },
  { name: 'Egypt',                   dialCode: '+20',  isoCode: 'EG', maxLength: 10 },
  { name: 'El Salvador',             dialCode: '+503', isoCode: 'SV', maxLength: 8  },
  { name: 'Estonia',                 dialCode: '+372', isoCode: 'EE', maxLength: 8  },
  { name: 'Ethiopia',                dialCode: '+251', isoCode: 'ET', maxLength: 9  },
  { name: 'Finland',                 dialCode: '+358', isoCode: 'FI', maxLength: 12 },
  { name: 'France',                  dialCode: '+33',  isoCode: 'FR', maxLength: 9  },
  { name: 'Georgia',                 dialCode: '+995', isoCode: 'GE', maxLength: 9  },
  { name: 'Germany',                 dialCode: '+49',  isoCode: 'DE', maxLength: 12 },
  { name: 'Ghana',                   dialCode: '+233', isoCode: 'GH', maxLength: 9  },
  { name: 'Greece',                  dialCode: '+30',  isoCode: 'GR', maxLength: 10 },
  { name: 'Guatemala',               dialCode: '+502', isoCode: 'GT', maxLength: 8  },
  { name: 'Honduras',                dialCode: '+504', isoCode: 'HN', maxLength: 8  },
  { name: 'Hong Kong',               dialCode: '+852', isoCode: 'HK', maxLength: 8  },
  { name: 'Hungary',                 dialCode: '+36',  isoCode: 'HU', maxLength: 9  },
  { name: 'Iceland',                 dialCode: '+354', isoCode: 'IS', maxLength: 9  },
  { name: 'Indonesia',               dialCode: '+62',  isoCode: 'ID', maxLength: 12 },
  { name: 'Iran',                    dialCode: '+98',  isoCode: 'IR', maxLength: 10 },
  { name: 'Iraq',                    dialCode: '+964', isoCode: 'IQ', maxLength: 10 },
  { name: 'Ireland',                 dialCode: '+353', isoCode: 'IE', maxLength: 9  },
  { name: 'Israel',                  dialCode: '+972', isoCode: 'IL', maxLength: 9  },
  { name: 'Italy',                   dialCode: '+39',  isoCode: 'IT', maxLength: 10 },
  { name: 'Jamaica',                 dialCode: '+1',   isoCode: 'JM', maxLength: 10 },
  { name: 'Japan',                   dialCode: '+81',  isoCode: 'JP', maxLength: 10 },
  { name: 'Jordan',                  dialCode: '+962', isoCode: 'JO', maxLength: 9  },
  { name: 'Kazakhstan',              dialCode: '+7',   isoCode: 'KZ', maxLength: 10 },
  { name: 'Kenya',                   dialCode: '+254', isoCode: 'KE', maxLength: 9  },
  { name: 'Kuwait',                  dialCode: '+965', isoCode: 'KW', maxLength: 8  },
  { name: 'Kyrgyzstan',              dialCode: '+996', isoCode: 'KG', maxLength: 9  },
  { name: 'Laos',                    dialCode: '+856', isoCode: 'LA', maxLength: 9  },
  { name: 'Latvia',                  dialCode: '+371', isoCode: 'LV', maxLength: 8  },
  { name: 'Lebanon',                 dialCode: '+961', isoCode: 'LB', maxLength: 8  },
  { name: 'Libya',                   dialCode: '+218', isoCode: 'LY', maxLength: 9  },
  { name: 'Lithuania',               dialCode: '+370', isoCode: 'LT', maxLength: 8  },
  { name: 'Luxembourg',              dialCode: '+352', isoCode: 'LU', maxLength: 9  },
  { name: 'Macau',                   dialCode: '+853', isoCode: 'MO', maxLength: 8  },
  { name: 'Madagascar',              dialCode: '+261', isoCode: 'MG', maxLength: 9  },
  { name: 'Malawi',                  dialCode: '+265', isoCode: 'MW', maxLength: 9  },
  { name: 'Malaysia',                dialCode: '+60',  isoCode: 'MY', maxLength: 11 },
  { name: 'Maldives',                dialCode: '+960', isoCode: 'MV', maxLength: 7  },
  { name: 'Mali',                    dialCode: '+223', isoCode: 'ML', maxLength: 8  },
  { name: 'Malta',                   dialCode: '+356', isoCode: 'MT', maxLength: 8  },
  { name: 'Mauritius',               dialCode: '+230', isoCode: 'MU', maxLength: 8  },
  { name: 'Mexico',                  dialCode: '+52',  isoCode: 'MX', maxLength: 10 },
  { name: 'Moldova',                 dialCode: '+373', isoCode: 'MD', maxLength: 8  },
  { name: 'Mongolia',                dialCode: '+976', isoCode: 'MN', maxLength: 8  },
  { name: 'Montenegro',              dialCode: '+382', isoCode: 'ME', maxLength: 8  },
  { name: 'Morocco',                 dialCode: '+212', isoCode: 'MA', maxLength: 9  },
  { name: 'Mozambique',              dialCode: '+258', isoCode: 'MZ', maxLength: 9  },
  { name: 'Myanmar',                 dialCode: '+95',  isoCode: 'MM', maxLength: 9  },
  { name: 'Namibia',                 dialCode: '+264', isoCode: 'NA', maxLength: 9  },
  { name: 'Nepal',                   dialCode: '+977', isoCode: 'NP', maxLength: 10 },
  { name: 'Netherlands',             dialCode: '+31',  isoCode: 'NL', maxLength: 9  },
  { name: 'New Zealand',             dialCode: '+64',  isoCode: 'NZ', maxLength: 9  },
  { name: 'Nicaragua',               dialCode: '+505', isoCode: 'NI', maxLength: 8  },
  { name: 'Nigeria',                 dialCode: '+234', isoCode: 'NG', maxLength: 10 },
  { name: 'Norway',                  dialCode: '+47',  isoCode: 'NO', maxLength: 8  },
  { name: 'Oman',                    dialCode: '+968', isoCode: 'OM', maxLength: 8  },
  { name: 'Pakistan',                dialCode: '+92',  isoCode: 'PK', maxLength: 10 },
  { name: 'Palestine',               dialCode: '+970', isoCode: 'PS', maxLength: 9  },
  { name: 'Panama',                  dialCode: '+507', isoCode: 'PA', maxLength: 8  },
  { name: 'Paraguay',                dialCode: '+595', isoCode: 'PY', maxLength: 9  },
  { name: 'Peru',                    dialCode: '+51',  isoCode: 'PE', maxLength: 9  },
  { name: 'Philippines',             dialCode: '+63',  isoCode: 'PH', maxLength: 10 },
  { name: 'Poland',                  dialCode: '+48',  isoCode: 'PL', maxLength: 9  },
  { name: 'Portugal',                dialCode: '+351', isoCode: 'PT', maxLength: 9  },
  { name: 'Qatar',                   dialCode: '+974', isoCode: 'QA', maxLength: 8  },
  { name: 'Romania',                 dialCode: '+40',  isoCode: 'RO', maxLength: 9  },
  { name: 'Russia',                  dialCode: '+7',   isoCode: 'RU', maxLength: 10 },
  { name: 'Rwanda',                  dialCode: '+250', isoCode: 'RW', maxLength: 9  },
  { name: 'Saudi Arabia',            dialCode: '+966', isoCode: 'SA', maxLength: 9  },
  { name: 'Senegal',                 dialCode: '+221', isoCode: 'SN', maxLength: 9  },
  { name: 'Serbia',                  dialCode: '+381', isoCode: 'RS', maxLength: 9  },
  { name: 'Singapore',               dialCode: '+65',  isoCode: 'SG', maxLength: 8  },
  { name: 'Slovakia',                dialCode: '+421', isoCode: 'SK', maxLength: 9  },
  { name: 'Slovenia',                dialCode: '+386', isoCode: 'SI', maxLength: 8  },
  { name: 'South Africa',            dialCode: '+27',  isoCode: 'ZA', maxLength: 9  },
  { name: 'South Korea',             dialCode: '+82',  isoCode: 'KR', maxLength: 10 },
  { name: 'Spain',                   dialCode: '+34',  isoCode: 'ES', maxLength: 9  },
  { name: 'Sri Lanka',               dialCode: '+94',  isoCode: 'LK', maxLength: 9  },
  { name: 'Sudan',                   dialCode: '+249', isoCode: 'SD', maxLength: 9  },
  { name: 'Sweden',                  dialCode: '+46',  isoCode: 'SE', maxLength: 9  },
  { name: 'Switzerland',             dialCode: '+41',  isoCode: 'CH', maxLength: 9  },
  { name: 'Syria',                   dialCode: '+963', isoCode: 'SY', maxLength: 9  },
  { name: 'Taiwan',                  dialCode: '+886', isoCode: 'TW', maxLength: 9  },
  { name: 'Tajikistan',              dialCode: '+992', isoCode: 'TJ', maxLength: 9  },
  { name: 'Tanzania',                dialCode: '+255', isoCode: 'TZ', maxLength: 9  },
  { name: 'Thailand',                dialCode: '+66',  isoCode: 'TH', maxLength: 9  },
  { name: 'Tunisia',                 dialCode: '+216', isoCode: 'TN', maxLength: 8  },
  { name: 'Turkey',                  dialCode: '+90',  isoCode: 'TR', maxLength: 10 },
  { name: 'Turkmenistan',            dialCode: '+993', isoCode: 'TM', maxLength: 8  },
  { name: 'Uganda',                  dialCode: '+256', isoCode: 'UG', maxLength: 9  },
  { name: 'Ukraine',                 dialCode: '+380', isoCode: 'UA', maxLength: 9  },
  { name: 'United Arab Emirates',    dialCode: '+971', isoCode: 'AE', maxLength: 9  },
  { name: 'United Kingdom',          dialCode: '+44',  isoCode: 'GB', maxLength: 10 },
  { name: 'United States',           dialCode: '+1',   isoCode: 'US', maxLength: 10 },
  { name: 'Uruguay',                 dialCode: '+598', isoCode: 'UY', maxLength: 8  },
  { name: 'Uzbekistan',              dialCode: '+998', isoCode: 'UZ', maxLength: 9  },
  { name: 'Venezuela',               dialCode: '+58',  isoCode: 'VE', maxLength: 10 },
  { name: 'Vietnam',                 dialCode: '+84',  isoCode: 'VN', maxLength: 10 },
  { name: 'Yemen',                   dialCode: '+967', isoCode: 'YE', maxLength: 9  },
  { name: 'Zambia',                  dialCode: '+260', isoCode: 'ZM', maxLength: 9  },
  { name: 'Zimbabwe',                dialCode: '+263', isoCode: 'ZW', maxLength: 9  },
]

export function getDefaultCountry(list = COUNTRY_CODES) {
  return list.find(c => c.isoCode === 'IN') ?? list[0]
}

export function sanitizePhoneNumber(value) {
  return value.replace(/\D/g, '')
}

export function validatePhoneNumberForCountry({ phoneNumber, dialCode }) {
  const digits = sanitizePhoneNumber(phoneNumber)
  if (!digits) return { isValid: false, message: 'Phone number is required', digits: '' }
  if (digits.length < 6)  return { isValid: false, message: 'Phone number is too short', digits }
  if (digits.length > 15) return { isValid: false, message: 'Phone number is too long', digits }
  const country = COUNTRY_CODES.find(c => c.dialCode === dialCode)
  if (country?.maxLength && digits.length !== country.maxLength) {
    return { isValid: false, message: `Must be ${country.maxLength} digits for ${dialCode}`, digits }
  }
  return { isValid: true, message: '', digits }
}
